stages:
    - build
    - deploy

build:
    image: alpine:latest
    stage: build
    artifacts:
        paths:
            - public/
    only:
        - master
    before_script:
        - apk add --update --no-cache git npm curl
        - curl -L https://github.com/gohugoio/hugo/releases/download/v0.60.1/hugo_extended_0.60.1_Linux-64bit.tar.gz | tar -xz hugo && mv hugo /usr/bin
        - git submodule sync --recursive
        - npm install
    script:
        - hugo

deploy:
    image: mesosphere/aws-cli:latest
    stage: deploy
    only:
        - master
    script:
        - aws s3 sync public s3://synecdoche.dev --delete
    environment:
        name: production
        url: https://synecdoche.dev