stages:
    - build
    - deploy

build:
    image: registry.gitlab.com/pages/hugo/hugo_extended:latest
    stage: build
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    artifacts:
        paths:
            - public/
    only:
        - master
    before_script:
        - npm install
    script:
        - hugo

deploy:
    image: mesosphere/aws-cli:latest
    stage: deploy
    only:
        - master
    script:
        - aws s3 sync public s3://synecdoche.dev --delete
    environment:
        name: production
        url: https://synecdoche.dev